music={
    "sway":"https://www.youtube.com/watch?v=VmZ8pKZUVfY&list=RDVmZ8pKZUVfY&start_radio=1",
    "What Makes You Beautiful":"https://www.youtube.com/watch?v=QJO3ROT-A4E",
    "Night Changes":"https://www.youtube.com/watch?v=3H7Qj1aYxY8",
    "Lose Yourself":"https://www.youtube.com/watch?v=_Yhyp-_hX2s",
    "Love The Way You Lie":"https://www.youtube.com/watch?v=uelHwf8o7_U",
    "Beautiful Things":"https://www.youtube.com/watch?v=Q-1c0n9vX3Y",
    "Faded":"https://www.youtube.com/watch?v=60ItHLz5WEA",
    "Alone":"https://www.youtube.com/watch?v=1-xGerv5FOY",
    "Mockingbird":"https://www.youtube.com/watch?v=5qap5aO4i9A",
    "Memories":"https://www.youtube.com/watch?v=SlPhMPnQ58k",
    "Criminal":"https://www.youtube.com/watch?v=2nMZkK3Jk8w",
    "Let Me Love You":"https://www.youtube.com/watch?v=0yW7w8F2TVA",
    "Believer":"https://www.youtube.com/watch?v=7wtfhZwyrcc",
    "Thunder":"https://www.youtube.com/watch?v=fKopy74weus",
    "Radioactive":"https://www.youtube.com/watch?v=ktvTqknDobU",
    "Demons":"https://www.youtube.com/watch?v=mWRsgZuwf_8",
    "On My Way":"https://www.youtube.com/watch?v=60ItHLz5WEA",
}
